### ISSUE TITLE
Website blank on custom domain

### ISSUE THREAD

**Issue by nickserv** [DefinitelyTyped/definitelytyped.github.io#103]
If you visit https://www.definitelytyped.org/, this is the only content displayed:

> # webseo1

However, https://definitelytyped.github.io/ does work properly.

Please either fix the custom domain or replace links to the subdomain.

**Comment by akaabdullahmateen** [comment]
I can confirm that the issue is as @nickmccurdy explained.

**Comment by smith558** [comment]
This is still an issue.
