### ISSUE TITLE
chrome.app.d.ts incorrect

### ISSUE THREAD

**Issue by nhrones** [DefinitelyTyped/definitelytyped.github.io#30]
The <chrome.app.d.ts> file is incorrect.
In module 'chrome.app.window', there are several 'vars' declared near the end, that represent events of the AppWindow interface. They need to be moved to 'interface AppWindow' in the same module.
Modules(namespaces) can't have events. These events were incorrectly or vaguely documented on Google's documentation for 'chrome.app.window'.

**Comment by basarat** [comment]
Please move to this repository : https://github.com/borisyankov/DefinitelyTyped/issues to have someone fix it.
