### ISSUE TITLE
angularjs.TypeScript.DefinitelyTyped NuGet package has dependency on out of date jquery.TypeScript.DefinitelyTyped NuGet package

### ISSUE THREAD

**Issue by apulliam** [DefinitelyTyped/definitelytyped.github.io#47]
I was installing 4.3.0 angularjs.TypeScript.DefinitelyTyped with NuGet and noticed I was getting 222 errors in the jquery TS definitions.  Took a while to figure out that angularjs.TypeScript.DefinitelyTyped installs an out-of-date jquery.TypeScript.DefinitelyTyped NuGet package.  Once I manually updated to 2.3.1 the errors went away, but wanted to let the NuGet package owner to update the dependency - since the issue wasn't obvious at first and may cause dev's to needlessly waste time tracking down (as I did :-) )
-Alan

**Comment by staxmanade** [comment]
Thanks @apulliam - this seems to be a bug in NuGet (or so we think) there is not a 'version' specified in the `.nuspec` which should tell it to pull the most recent version (which it doesn't in some cases).

**Comment by apulliam** [comment]
Hi Jason.  Thanks for the follow-up.  I’m a Technical Evangelist for Microsoft.  Can you provide a little more detail?  I’d be happy to connect you with our folks who work with NuGet to see if we can figure out the problem.

-Alan

Alan Pulliam
Technical Evangelist
Microsoft Developer Experience (DX)

**Comment by staxmanade** [comment]
@apulliam would be great if you could look into this or get someone else to look into it further.

Here's another issue where we discuss item: https://github.com/borisyankov/DefinitelyTyped/issues/5446

I don't have time to dig into NuGet specifically to find out further at the moment. Hope this helps.

**Comment by apulliam** [comment]
Hi Jason,

Not sure if I’m going to be successful, but I’ve tried to start a thread with our folks who work with NuGet.

Please send me your direct email and I’ll include you on the thread – if it make progress ;-)

-Alan

**Comment by staxmanade** [comment]
For anyone running into this issue: check the following setting in Visual Studio:

![image](https://cloud.githubusercontent.com/assets/156715/10861918/92beaf8e-7f50-11e5-9ef0-ca87aa8f5d12.png)

The default behavior may not have been “Lowest” before which may explain why this issue is new to Visual Studio 2015.  To get things to work with the current angular TS definition package, you need to  choose "highest" when you install or upgrade your package.
