### ISSUE TITLE
breeze.ISaveResult is invalid

### ISSUE THREAD

**Issue by ts46235** [DefinitelyTyped/definitelytyped.github.io#50]
It should now be:

    interface SaveResult {
        entities: Entity[];
        keyMappings: any;
        httpResponse: HttpResponse;
    }

see http://breeze.github.io/doc-js/api-docs/classes/EntityManager.html#method_saveChanges

**Comment by staxmanade** [comment]
@ts46235 please look to send a pull request to the https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/breeze file(s)...
