### ISSUE TITLE
tsdpm.org is now stuck in redirect loops to definitelytyped.org/tsd :(

### ISSUE THREAD

**Issue by jskrzypek** [DefinitelyTyped/definitelytyped.github.io#51]
I can't access either one.

**Comment by vvakame** [comment]
@DefinitelyTyped/contributors can any one fix this issue?

**Comment by alfkonee** [comment]
Please Whats the status of this site still seems broken

**Comment by vvakame** [comment]
I'm removing tsd links.

**Comment by download13** [comment]
I'm still having this problem. Can't access the tsdpm.org site.

**Comment by G-Laser** [comment]
So, should we expect the TSD links to be removed from the definitelytyped.org site? They're still there and they're still broken and makes the project seem a bit sloppy and poorly maintained.

**Comment by moll** [comment]
http://definitelytyped.org/tsd/ seems to refer to a site now that hosts pictures of barely naked ladies. :dancing_women:
