### ISSUE TITLE
Broken link on http://definitelytyped.org/

### ISSUE THREAD

**Issue by 0815fox** [DefinitelyTyped/definitelytyped.github.io#54]
The link to `http://ww2.tsdpm.org/` on the main page to the TSD is broken, the domain is expired. Is there an alternative link to the typings database?

**Comment by SaschaNaz** [comment]
This is changed to `http://definitelytyped.org/tsd/` but still does not show any valid page.

**Comment by SaschaNaz** [comment]
No update on this?

**Comment by sargin48** [comment]
I will f__ck your job. 
definitelytyped.org/tsd/ closed for months

**Comment by johnnyreilly** [comment]
That's not helpful @sargin48. For anyone who finds this link, TSD is deprecated and has been for a long time. Typings is what you should be looking for if you want a replacement. Courtesy of the hard work of @blakeembrey. You're welcome.

**Comment by SaschaNaz** [comment]
Please do not close this issue when http://definitelytyped.org/ still shows the TSD button without any warning.

**Comment by johnnyreilly** [comment]
We're open to a PR that removes it - or better yet one that replaces it with a link to Typings instead.

**Comment by blakeembrey** [comment]
Linking to the docs on using NPM's `@types` feature might be the best solution now 😄  I'm hoping I'll be able to replace Typings soon enough with native TypeScript support of third-party definitions.

**Comment by johnnyreilly** [comment]
Oh wow - does that mean Typings will be no more? 😯

**Comment by blakeembrey** [comment]
Not right now, waiting on https://github.com/Microsoft/types-publisher/issues/4, but hopefully. Typings will continue to be maintained, of course, but mostly it'll be deprecated except for the few advanced use-cases TypeScript doesn't support.

**Comment by johnnyreilly** [comment]
Ah cool - nice that the language is now starting to deal with some of the pain points you identified. 👍

**Comment by DavidDeSloovere** [comment]
This link has already been removed in the sources.
https://github.com/DefinitelyTyped/definitelytyped.github.io/commit/5fcdb3388d0bac0a46b2736e7cfe00351a8d0e6c

Anyone know why the site isn't updated yet?

Pretty sure a lot of people click the TSD link and get a bit annoyed by the result.

**Comment by vvakame** [comment]
I fixed deployment issue. site was updated. 😉 
I think many contents needs some update...
