### ISSUE TITLE
http://definitelytyped.org/tsd not accessible

### ISSUE THREAD

**Issue by ranjan-ranjan** [DefinitelyTyped/definitelytyped.github.io#55]
Whereever http://definitelytyped.org/tsd/ is given, it should be removed as it is not accessible.

**Comment by Diullei** [comment]
Hi @ranjan-ranjan Thanks for reporting it. We are working in a new version of DT website. http://definitelytyped.herokuapp.com/ it will be published soon.

**Comment by ranjan-ranjan** [comment]
that will be better, because this website have many bugs and not properly organized.
