### ISSUE TITLE
Is definitelytyped.org depricated?

### ISSUE THREAD

**Issue by gavinr** [DefinitelyTyped/definitelytyped.github.io#71]
Although there are contributions of issues and PRs from the community, there appears to be no updates of this website. It has a link to a [spam site in the main navigation](https://github.com/DefinitelyTyped/definitelytyped.github.io/issues/54), and the site seems overall un-cared for. 

"There hasn’t been any commit activity on DefinitelyTyped/definitelytyped.github.io in the last month."
https://github.com/DefinitelyTyped/definitelytyped.github.io/pulse/monthly

Is this site dead? It's confusing because https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master is so active.

**Comment by johnnyreilly** [comment]
It's a reasonable question. I'm one of the core team and I've long forgotten who was last maintaining the site. There's been various talks about revamps (last when the TypeScript folks joined DT) but for whatever reason it's never happened.

**Comment by vvakame** [comment]
I just start to maintainance this site.
But I'll not update the contents. I will review & merge PRs only.

**Comment by gavinr** [comment]
Thanks @vvakame for picking up the maintenance!
