### ISSUE TITLE
site.github links aren't rendering correctly on some pages

### ISSUE THREAD

**Issue by nschonni** [DefinitelyTyped/definitelytyped.github.io#75]
Maybe a markdown difference in who docpad treats them. I have one other idea to try, but currently the links render as `http://definitelytyped.org/directory/%-%20@site.github%20%`

**Comment by vvakame** [comment]
We fixed http://definitelytyped.org/directory/learn.html .
Does any other broken links exists?

**Comment by nschonni** [comment]
Not sure about any other types of broken links, but searching through the repo it doesn't look like any of the other `site.github` references are affected
