### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by GirlBossRush** [DefinitelyTyped/definitelytyped.github.io#80]
I'm a big fan of TypeScript. Would it be possible to add HTTPS to definitelytyped.org? Cloudflare and Lets Encrypt are free too 😃 

Cheers

**Comment by bapcltd-marv** [comment]
It's got https now, but it's not enabled by default/ no redirect etc.

**Comment by jakebailey** [comment]
The site is now hosted in github pages, which does HTTPS and redirects for us.
