### ISSUE TITLE
Can't get to docs from homepage.

### ISSUE THREAD

**Issue by NullPainter2** [DefinitelyTyped/definitelytyped.github.io#97]
Hi, there is no link on homepage which leads to http://definitelytyped.org/docs/ .

**Comment by DamianArado** [comment]
Apparently, we can visit those at: https://definitelytyped.github.io/

**Comment by NullPainter2** [comment]
@DamianArado Thanks for reply. What docs do You mean? https://www.typescriptlang.org/dt/search?search= ?

Anyway.

Closing issue, page I mentioned returns 404 now.
